spring:
  profiles:
    active: @activatedProperties@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 0
      maximum-pool-size: 100
      connection-timeout: 60000
      idle-timeout: 600000
      max-lifetime: 1800000
  redis:
    database: 1



mybatis:
  mapper-locations: classpath:mapperxml/*.xml


