spring:
  profiles:
    active: @activatedProperties@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 0
      maximum-pool-size: 100
      connection-timeout: 60000
      idle-timeout: 600000
      max-lifetime: 1800000
  redis:
    database: 1
    timeout: 500
    lettuce:
      pool:
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0
        # 连接池中的最大空闲连接 默认为 0
        max-idle: 50
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1ms
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 10





mybatis:
  mapper-locations: classpath:mapperxml/*.xml


