spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: Huangjie@123
    url: jdbc:p6spy:mysql:replication://39.107.203.227:3306/shiro?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 0
      maximum-pool-size: 100
      connection-timeout: 60000
      idle-timeout: 600000
      max-lifetime: 1800000

mybatis:
  mapper-locations: classpath:mapperxml/*.xml

my:
  dubbo:
    appname: study_shiro
  shutdown:
    port: 12315
  zookeeper: zookeeper.axxvip.com:2181

server:
  port: 2356

